# Generated by Django 5.1.1 on 2024-09-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('MEM', 'Member'), ('LIB', 'Librarian'), ('ADM', 'Admin')], default='MEM', max_length=3),
        ),
    ]
