# Generated by Django 5.1.1 on 2024-09-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_user_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='User1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('roll', models.IntegerField()),
                ('department', models.CharField(choices=[('CMT', 'Computer Technology'), ('ENT', 'Electronics Technology'), ('RAC', 'Refrigeration and Air Conditioning Technology'), ('FD', 'Food Technology')], max_length=15)),
                ('session', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('user_type', models.CharField(choices=[('MEM', 'Member'), ('LIB', 'Librarian'), ('ADM', 'Admin')], max_length=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='profiles/')),
            ],
        ),
    ]
