# Generated by Django 5.1.1 on 2024-09-06 10:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('bio', models.TextField(blank=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(choices=[('SL', 'Select Country Name'), ('BD', 'Bangladesh'), ('IN', 'India'), ('US', 'United States'), ('CA', 'Canada'), ('AU', 'Australia'), ('GB', 'United Kingdom'), ('CN', 'China'), ('JP', 'Japan'), ('DE', 'Germany'), ('FR', 'France'), ('BR', 'Brazil'), ('ZA', 'South Africa'), ('RU', 'Russia'), ('MX', 'Mexico'), ('IT', 'Italy'), ('ES', 'Spain'), ('NG', 'Nigeria'), ('AR', 'Argentina'), ('SA', 'Saudi Arabia'), ('KR', 'South Korea'), ('ID', 'Indonesia'), ('TR', 'Turkey'), ('EG', 'Egypt'), ('PK', 'Pakistan'), ('NL', 'Netherlands'), ('SE', 'Sweden'), ('CH', 'Switzerland'), ('BE', 'Belgium'), ('PL', 'Poland'), ('MY', 'Malaysia'), ('PH', 'Philippines'), ('TH', 'Thailand'), ('IR', 'Iran'), ('IQ', 'Iraq'), ('VN', 'Vietnam'), ('IL', 'Israel'), ('NO', 'Norway'), ('FI', 'Finland'), ('NZ', 'New Zealand'), ('SG', 'Singapore'), ('AE', 'United Arab Emirates'), ('GR', 'Greece'), ('PT', 'Portugal'), ('CZ', 'Czech Republic'), ('HU', 'Hungary'), ('AT', 'Austria'), ('DK', 'Denmark'), ('IE', 'Ireland'), ('CL', 'Chile'), ('RO', 'Romania'), ('KE', 'Kenya')], default='SL', max_length=30)),
                ('image', models.ImageField(blank=True, null=True, upload_to='author_image/')),
            ],
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('isbn', models.CharField(max_length=13)),
                ('published_date', models.DateField()),
                ('Language', models.CharField(choices=[('BD', 'Bangla'), ('PK', 'Urdu'), ('LN', 'Select Book Language'), ('IN', 'Hindi'), ('EN', 'English'), ('FR', 'French'), ('ES', 'Spanish'), ('DE', 'German'), ('CN', 'Mandarin'), ('JP', 'Japanese'), ('RU', 'Russian'), ('IT', 'Italian'), ('PT', 'Portuguese'), ('AR', 'Arabic'), ('KR', 'Korean'), ('TR', 'Turkish')], default='LN', max_length=30)),
                ('available_copies', models.IntegerField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='book_image/')),
                ('description', models.TextField(blank=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.author')),
                ('entry_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='books.bookcategory')),
            ],
        ),
    ]
