# Generated by Django 5.1.1 on 2024-09-07 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='Language',
            new_name='language',
        ),
    ]
